### ISSUE TITLE
Some parts of the website is blurry

### ISSUE THREAD

**Issue by alixsep** [PiyushSuthar/Windows-11-Web#11]
for example windows instances and desktop 
![image](https://user-images.githubusercontent.com/59757582/127266647-b39502c4-1dbe-499e-a5bf-0455181ef529.png)

start menu text is good and crisp though :)

**Comment by PiyushSuthar** [comment]
According to this stackoverflow, it's a bug in chrome and chromium browser.
( I can confirm it, since I have tested on all the browsers. And it blurred only on chromium based browsers)

https://stackoverflow.com/questions/27385126/chrome-font-appears-blurry

It's happening because of `transform` css property.
This might fix the issue, 
```css
#the_element_that_you_applied_translate_to {
  -webkit-font-smoothing: antialiased;
}
```

Do let me know if you would like to test and give a PR.
